using NPlot;
using Sunny.UI;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Linq;
using System.Net;
using System.Text;
using UCM_Tools.Config;

namespace UCM_Tools.Tools
{
    public class NplotCls
    {

        /// <summary>
        /// 当前目标  类型为0
        /// </summary>
        private LabelPointPlot str_LablePoint = new LabelPointPlot();


        public void Init(NPlot.Windows.PlotSurface2D plot, int hMin, int hMax, int vMin, int vMax, string h, string v)
        {
            Color colorLine = SystemSetting.VTKBackColor ? Color.LightGray : Color.FromArgb(150, 150, 150);
            Color coloLabel = SystemSetting.VTKBackColor ? Color.Black : Color.White;
            Color backColor = SystemSetting.VTKBackColor ? Color.White : Color.FromArgb(20, 0, 0);
            Color foreColor = SystemSetting.VTKBackColor ? Color.FromArgb(255, 100, 100) : Color.White;
            plot.AutoScaleAutoGeneratedAxes = true;
            plot.AutoScaleTitle = true;
            plot.DateTimeToolTip = false;
            plot.Dock = System.Windows.Forms.DockStyle.Fill;
            plot.Legend = null;
            plot.LegendZOrder = -1;
            plot.Location = new System.Drawing.Point(0, 0);
            plot.RightMenu = null;
            plot.RightToLeft = System.Windows.Forms.RightToLeft.No;
            plot.ShowCoordinates = false;
            plot.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            plot.Name = h + v;
            plot.TabIndex = 0;
            plot.Clear();
            plot.ForeColor = foreColor;
            plot.BackColor = backColor;

            //------区域着色------

            LinePlot lp1 = new LinePlot();
            lp1.Color = colorLine;
            lp1.AbscissaData = new double[] { hMin, hMax };
            lp1.OrdinateData = new double[] { vMax, vMax };
            plot.Add(lp1);
            LinePlot lp2 = new LinePlot();
            lp2.Color = colorLine;
            lp2.AbscissaData = new double[] { hMin, hMax };
            lp2.OrdinateData = new double[] { vMin, vMin };
            plot.Add(lp2);
            FilledRegion fr = new FilledRegion(lp1, lp2);
            fr.Brush = new SolidBrush(backColor);
            plot.Add(fr);


            //------网格------
            Grid mygrid = new Grid();
            mygrid.MinorGridPen = new Pen(colorLine);
            
            mygrid.MajorGridPen = new Pen(colorLine);
            mygrid.HorizontalGridType = Grid.GridType.Coarse;
            plot.Add(mygrid);


            //
            str_LablePoint.AbscissaData = null;
            str_LablePoint.OrdinateData = null;
            str_LablePoint.TextData = null;
            str_LablePoint.Marker = new Marker(Marker.MarkerType.FilledCircle, 10, new Pen(SystemSetting.TrackColor, 1.0F));
            str_LablePoint.Font = new Font("Times New Roman", 9);
            str_LablePoint.TextBrush  = new SolidBrush(SystemSetting.TrackTextColor);
            plot.Add(str_LablePoint);

            // 设置坐标系的大小
            plot.XAxis1.Color = colorLine;
            plot.XAxis1.WorldMin = hMin;
            plot.XAxis1.WorldMax = hMax;
            plot.XAxis1.Label = h;
            plot.XAxis1.LabelColor = coloLabel;
            plot.XAxis1.LabelOffset = 5;
            plot.YAxis1.Color = colorLine;
            plot.YAxis1.WorldMin = vMin;
            plot.YAxis1.WorldMax = vMax;
            plot.YAxis1.Label = v;
            plot.YAxis1.TicksLabelAngle = 0;
            plot.YAxis1.LabelColor = coloLabel;
            plot.Refresh();
        }

        

        public void SetCurrentValueToNplot(List<double> H, List<double> V, List<string> text)
        {
            if (H == null || V == null || text == null || H.Count <= 0 || V.Count <= 0 || text.Count <= 0)
            {
                str_LablePoint.AbscissaData = null;
                str_LablePoint.OrdinateData = null;
                str_LablePoint.TextData = null;
            }
            else
            {
                double[] xr_Other = new double[H.Count];
                double[] yr_Other = new double[V.Count];
                string[] textr_Other = new string[text.Count];
                H.CopyTo(xr_Other);
                V.CopyTo(yr_Other);
                text.CopyTo(textr_Other);
                str_LablePoint.AbscissaData = xr_Other;
                str_LablePoint.OrdinateData = yr_Other;
                str_LablePoint.TextData = textr_Other;
            }
        }
    }
}
